### ISSUE TITLE
Make A navbar 

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/lets-Upsolve#1]
We need a Navbar to support routing in our application.

**Comment by himanshu1221** [comment]
Hey @shrinish123 i can make a responsive navbar as you want can you please assign this to me under KWoC

**Comment by himanshu1221** [comment]
@shrinish123 thanks for assigning me the task..i have a query that what table of content you want in your navbar

**Comment by himanshu1221** [comment]
@shrinish123 i already made it with **bootstrap** but as you have mentioned to **MUI** i will try my best to dilever you this within **2 days**

**Comment by shrinish123** [comment]
So further on  I am planning or backend and also have users login sign up, etc , So it should look something like this : 
![Screenshot 2022-12-04 183954](https://user-images.githubusercontent.com/56491104/205492355-a8e1bdb1-eade-4ef6-87ec-00a92b5eba65.png)
And change the other contents with tagsPractice , upsolve contests, suggested practice, Analysis ,etc and probably a theme like the dark theme of material UI
