### ISSUE TITLE
Feature to search for a CF round just by its name 

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/lets-Upsolve#19]
So right now, I don't see a way to find if I want to see a round let's say CF round 661 (Div 3). how to find it on CF particularly or the contest page. It would be a good idea to implement this on this platform.

**Comment by Shreya-Agrawal-2121** [comment]
@shrinish123 I am interested to work on this issue. Pls assign it to me for KWoc'22

**Comment by shrinish123** [comment]
Cool @Shreya-Agrawal-2121 . assigning it to you.
