### ISSUE TITLE
Change title and favicon along with designing logo

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/lets-Upsolve#6]
Right now we dont have a proper favicon and title for our web app

**Comment by hemanthraj2001** [comment]
Hello @shrinish123 ,
I want to work on this issue. Could you please assign me? I am participating in KWoC'22.

**Comment by hemanthraj2001** [comment]
I will complete it by tomorrow evening.

**Comment by hemanthraj2001** [comment]
By the way any suggestions from your side that must be included in the logo?
