### ISSUE TITLE
Add styling on suggested practice for showing current selected level 

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/lets-Upsolve#7]

**Comment by hemanthraj2001** [comment]
Hi @shrinish123, I want to solve this issue. Could you please assign this issue to me?

**Comment by shrinish123** [comment]
Ok I would assign this issue to you for now. 

![step](https://user-images.githubusercontent.com/56491104/206380363-9e4ccc03-ce1c-403b-9e4b-142a2948b25e.png)

I am expecting something like this. This is available on material UI navigation. 
But remove the two buttons next and complete step , as we don't want them there right now . 
Also, make proper changes to the already available code by material UI so that code is clean and precise. 
Please do not  just copy paste it .
Looking forward to your contribution.
