### ISSUE TITLE
Add a Page to add good blogs of codeforces 

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/lets-Upsolve#9]
There can be the page for a compilation of good blogs on code forces and there can be also a form to add  a particular blog on this page

**Comment by Shreya-Agrawal-2121** [comment]
Hey @shrinish123, I am interested to work in this issue. Pls, assign it to me for KWoC'22.

**Comment by shrinish123** [comment]
Hello, @Shreya-Agrawal-2121 , I will assign this issue to you. But please do share your progress in steps to know where you are. Also do share the deadline for your PR submission. so right now  the only requirement is to have a title , and a list of blogs , where on clicking the blog it would redirect you to the blog on codeforces . Something similar to questions list . Right now just keep a static list, and then will improve over it with new PRs
